-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create users table for authentication


CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'Operator',
    factory_id VARCHAR(50),
    department VARCHAR(100),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP WITH TIME ZONE,
    
    -- Constraints
    CONSTRAINT chk_role CHECK (role IN ('Operator', 'Supervisor', 'Management'))
);

-- Indexes for performance

CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role);
CREATE INDEX IF NOT EXISTS idx_users_factory_id ON users(factory_id);
CREATE INDEX IF NOT EXISTS idx_users_is_active ON users(is_active);

-- Trigger to update updated_at timestamp

CREATE OR REPLACE FUNCTION update_users_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_users_updated_at();

-- Sample users for testing
-- Password for all users: "Password123!"
-- Hash generated by Flask application using bcrypt

INSERT INTO users (username, email, password_hash, role, factory_id, department) VALUES
    ('operator1', 'operator1@factory.com', '$2b$12$m9iA60jeR5AuatBCV9UPUel/MwmdXhsfzddLdaA54QcaTtXKtj3fu', 'Operator', 'factory-A', 'Production'),
    ('supervisor1', 'supervisor1@factory.com', '$2b$12$iXhekJ34xVDaOmni8GvDC.8eBu49RG9atJqZbtUHnvVVKa0ImAtrK', 'Supervisor', 'factory-A', 'Operations'),
    ('manager1', 'manager1@factory.com', '$2b$12$n9HvhqwuSB6MGz3PycRaQuCemlw8/L7XqTc0KouXIlkCozucsHfGa', 'Management', 'factory-A', 'Management')
ON CONFLICT (username) DO NOTHING;

-- Audit log table to track user actions

CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    username VARCHAR(50),
    role VARCHAR(20),
    action VARCHAR(100) NOT NULL,
    resource VARCHAR(255) NOT NULL,
    method VARCHAR(10),
    status_code INTEGER,
    ip_address VARCHAR(45),
    user_agent TEXT,
    request_body JSONB,
    response_body JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for audit logs

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id ON audit_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource ON audit_logs(resource);

COMMENT ON TABLE users IS 'User accounts for authentication and authorization';
COMMENT ON TABLE audit_logs IS 'Audit trail for all user actions on protected endpoints';

